version: '3.3'
services:
  db:
    image: mysql:5.7.16
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbpassword'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-dbdata/db:/var/lib/mysql'
  mysqlclient:
    build:  ./sqlite
    container_name: sqllite
    command: tail -F anything
  app:
    build:  ./app
    container_name: atm-endpoint-service
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 900M
    ports:
      - '8081:8080'
    expose:
      - '8081'
volumes:
  my-db:

networks:
  application-service-net: { }
